name: "Gary Flom's Seromns"
favicon: null
layout_spectrum: 0.0082
typography_spectrum: 0.11685816757380962
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f6'
    - '#50433a'
    - '#24160d'
    - '#dd9184'
    - '#96735d'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.028795671416446567
  rhythmicContrast: 0.351674065226689
purpose: []
